### ISSUE TITLE
using Docker for testing 

### ISSUE THREAD

**Issue by rijnhard** [logstash-plugins/logstash-patterns-core#176]
This is just a bit of an FYI:

When testing i used a docker container: 

docker-compose.yml (in root directory)
```yml
version: '2'

# this is for testing only
services:
    logstash-patterns-core:
        # https://hub.docker.com/_/jruby/
        image: jruby:9-onbuild
        command: ["bundle", "exec", "rspec"]
```

but you could do the same in a single docker line 
```bash
docker run -ti --rm jruby:9-onbuild bundle exec rspec
```

the `jruby:9-onbuild` onbuild container uses the current directory of where its built to look for a `Gemfile.lock`
